apiVersion: v1
kind: Pod
metadata:
  name: stern-logger
spec:
  containers:
  - name: stern-logger
    image: echalhoub/stern
    command: ["/bin/sh", "/.kube/log.sh"]
    volumeMounts:
    - name: data
      mountPath: "/data"
    - name: config-volume
      mountPath: "/.kube/"
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: psv01
  - name: config-volume
    configMap:
      name: stern-config
